sonar.projectKey=HKoppineni29_SonarDemo
sonar.organization=HKoppineni29
sonar.projectName=Sonar Demo

sonar.sourceEncoding=UTF-8

# Salesforce code
sonar.sources=force-app/main/default
sonar.tests=force-app/main/default/classes

# Optional (for coverage, can leave as is)
sonar.apex.coverage.reportPath=test-results/test-result-codecoverage.json
