sonar.projectKey=HKoppineni29_SonarDemo
sonar.organization=hkoppineni29
sonar.projectName=Sonar Demo

sonar.sourceEncoding=UTF-8

# Tell SonarCloud exactly where to look
sonar.sources=force-app/main/default/classes

# Force .cls files to be treated as Apex
sonar.apex.file.suffixes=.cls

# Ensure test classes are marked as tests only
sonar.test.inclusions=**/*Test.cls
sonar.exclusions=**/*Test.cls

# Optional: coverage (safe even if file missing)
sonar.apex.coverage.reportPath=test-results/test-result-codecoverage.json
