sonar.projectKey=HKoppineni29_SonarDemo
sonar.organization=hkoppineni29
sonar.projectName=Sonar Demo

sonar.sourceEncoding=UTF-8

sonar.sources=force-app/main/default
sonar.language=apex

sonar.test.inclusions=**/*Test.cls
sonar.exclusions=**/*Test.cls

